version: '2'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    container_name: kibana
    ports:
      - "0.0.0.0:5601:5601"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    links:
      - kibana
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    ports:
      - "0.0.0.0:9200:9200"
