version: '3'

services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:3.3.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:3.3.0
    links:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema_registry:
    container_name: schema_registry
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: schema_registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181

  kafka-rest:
    container_name: kafka-rest
    image: confluentinc/cp-kafka-rest:3.3.0
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema_registry:8081
      KAFKA_REST_HOST_NAME: kafka-rest
    links:
      - zookeeper
      - kafka
    ports:
      - 0.0.0.0:8082:8082
  
  kafka-ui:
    image: landoop/kafka-topics-ui
    environment:
      KAFKA_REST_PROXY_URL: http://kafka-rest:8082
    ports:
      - 0.0.0.0:8000:8000
